# Generated by Django 2.0.5 on 2018-06-07 02:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2018, 6, 7, 2, 57, 42, 787597, tzinfo=utc))),
                ('content', models.TextField()),
                ('reading_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NavTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powername', models.CharField(max_length=50, unique=True)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2018, 6, 7, 2, 57, 42, 787597, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('age', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=10)),
                ('worker', models.CharField(max_length=50)),
                ('ownersite', models.CharField(max_length=20, unique=True)),
                ('powername', models.ManyToManyField(to='blog.Power')),
            ],
        ),
    ]
