# Generated by Django 2.0.5 on 2018-06-07 03:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180607_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('githubUrl', models.URLField(max_length=50)),
                ('powerstack', models.TextField(max_length=1500)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 7, 3, 17, 42, 423597, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='power',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 7, 3, 17, 42, 423597, tzinfo=utc)),
        ),
    ]
