# Generated by Django 2.0 on 2018-06-20 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180607_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 9, 23, 56, 851310, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='power',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 9, 23, 56, 851310, tzinfo=utc)),
        ),
    ]
