# Generated by Django 2.0 on 2018-06-21 06:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180620_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 6, 36, 35, 296310, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='power',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 6, 36, 35, 296310, tzinfo=utc)),
        ),
    ]
